apiVersion: ENC[AES256_GCM,data:f4k=,iv:r4NDcA2YdjtTG+JNF3OuvJp66dmTkk5BUH+txvFOET0=,tag:SSRNS4RfHMcNiMjvnGiDqQ==,type:str]
kind: ENC[AES256_GCM,data:WY2rHm+1,iv:N33eh2bBV8wQMowfciugRjOhZVyQzKS7bDYMC4TQlpE=,tag:cM+jguJ0xCOHB16MY1o5Sg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RxApHZFJ92ls14eJPhtKO7/wJpE=,iv:G/kQWn/brzEqANfS0rhHRR2zyAK8D7Zg4hVGD8wC+5k=,tag:lliXsIrwU0og8EmFmWccuA==,type:str]
    namespace: ENC[AES256_GCM,data:05d6n3BgJtatWDOk,iv:+0ReCNsewachHVnNPw9xYQx0+WXM7dkdVa42iBZxlsY=,tag:OFNNNoESMSqj06OQd5vZeQ==,type:str]
type: ENC[AES256_GCM,data:JVPnQo6L,iv:yZEs8AsrRTL+OQ0Riwe7eyBIMb4ttqK+kLJFFv6eXts=,tag:+eEn3bOOVaLTccc7rgGZqA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:32LSNOVdSXNn1nmnATUW12pQXUpll2WRYXE+/he+MEUx5pBj8TWS7ZalcAG9Nu1I69QrZEA=,iv:fKlHcePRUjiqkSGP7LezLI6K0Wb59eyNvCGjXXB3CPE=,tag:QtLmpzwkQ5HDQuG/hdRY8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTlpCbmd3bDd2Z3U3Uks3
            Q3NHdU5FTno1ckI0NG5jOWozNFFmTHUxWHhvCjR4THZPQWo4R1VJOU5acWpQSjA5
            ZGRrK3ZUbXY4c2dqeGgzZU5Hbnp2VFkKLS0tIHhGbHdMNHZKdGd0c2hQeWdsU1di
            c05rdy9Fem9HeFZJVENsanBpaU1GR0kKkXk1do/6qtSYwp4583gqhYliIajW/WgU
            TtmK8GKkFYO4/8ZlOwQVmLm4iS8KND2BBz2mbxBHyfMZSda51e2gaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6v260f4z6za7df8t5x726h0q3uhnr89fkm2rjk3n3tk9xgfgsrqqj5dff
    lastmodified: "2026-06-02T21:16:37Z"
    mac: ENC[AES256_GCM,data:fh6AMnwHZz+v1kdMqtep0pCCtjmm80zM+Lp05CjZ48f0P7Q+WSGWa/+hSZlrBv59CQtRSXnuyxGX4HP7/mfGclca3V2AUmvwBGH4YSHNVtIfiaPoxgEFOsxkjuUhK0zhyT9ztcVuJH1/j4eNIMX2DVjo6OWoQ4KLtnx2AnP6lSs=,iv:CbCHQzYK2qzKk70ZNbVkH4a0NCxTmrdWf+BuYhKaTcg=,tag:UeGBDgz8IxSgw7lhnf2gNw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
