apiVersion: ENC[AES256_GCM,data:Ntg=,iv:WgH+1e2YsOzQkB/I2/zJ/BE8ERClJZjjepzEnOyeDW8=,tag:K3KF4yVVxUgb5uTdCNkT3w==,type:str]
kind: ENC[AES256_GCM,data:N1fzrrCH,iv:lKEcZEkqXfi/9CAE6jJQCYRH4ju23sXvk+hf36Vp8rY=,tag:nejAhPoL6i60y8VEeTKWiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AUL2iYPHX/oYPH3k0QQVrko=,iv:aR0F53Kd0O4W1SBMDsPho0SC8jqlk1KqxoDmCU4pZhg=,tag:RjLh/xCwKiK3mP7BapcKkw==,type:str]
    namespace: ENC[AES256_GCM,data:R/H24hod4+q0XmkPRxyXTDs=,iv:WqdlXDQGjeVc/rIqZgvd4/8P7yQdVpJi2JpmUUDUpKM=,tag:ogZhiMqXwCdlTHAJauKd4A==,type:str]
type: ENC[AES256_GCM,data:g+H8X8SI,iv:vOwh/he0nJ6ZRaHCGIqdlUZFU+b9/zSM7HWtSO53nnQ=,tag:gVSTtpKCnFjx4abai2MX3A==,type:str]
stringData:
    token: ENC[AES256_GCM,data:YzQY6uTiSnnwB2JkhJLGFG4fhlOQfsfaQ96f2BsQh3HomrGhUiqma+M2VBVCzGfwKVNTCJ4ncerCoohEfTuPCBm15S5GKQ1betKmef2NiAMt7gnzhaHFUSG6udXq902TzYWAiwAJ+JIjn6+h0U2ovaCDkSYIcHq88lwAAM5Ham+kuj/Z7Ey5OcAa64BKlpWkut6VaPq01YSUdT+QLYk9hwTS7t6eqm+D3R724oDroFpXKSADXpDyOw==,iv:KqawhYLrCC1WGEYiIk9aDJ0zT0eZwJrcqbrHJ33babg=,tag:bIrfUFrPMphk2ceoT2uI9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSjJrbFRBWndQZksxbDNz
            NGZxNW14bjh0YmF6OTQ5cDd4eFBQNFVlOVUwCjhsNDNxaU1qdytwRGxIODA2N1VV
            RUFia0pkVU9xWVNLdzE0VEkwMWpVU2cKLS0tIHFvMlRWMHlsM2MzTmliWGR6YXY0
            NnNUYjN6bzVtYWFlVStCZUdURnNmeTgKIs804bF1FYkNx8t0ZiEy2amjawPs/SIW
            8HMZodLMNdRqB+acAt6M8/DwM5ZEdGYe/XUoqB8F2tmf5OKbrJv/NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6v260f4z6za7df8t5x726h0q3uhnr89fkm2rjk3n3tk9xgfgsrqqj5dff
    lastmodified: "2026-06-02T00:06:43Z"
    mac: ENC[AES256_GCM,data:GZ/lOj9Xhk18rnYuO9oiyCA/Ny5IGCbrzGkoDQB2eNmP1WsDK0597VY7Gu0qOwlyB4CXGAbaSe0WhxicSc+O0mStTP/2wbfNzH1LPeEeps8fmI+KUkPlzqHXBvP83cqY40EQdEhzn6VArc9QIguPfl5o1QGd5A67IiJLALix/i8=,iv:Iq6a4Zku2htp6Pq3I/ymRL8KHTJ0vvLzw4HEKFQVJvw=,tag:Oah5kcjW9W8ME3whYic9JA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
