apiVersion: ENC[AES256_GCM,data:Ntg=,iv:WgH+1e2YsOzQkB/I2/zJ/BE8ERClJZjjepzEnOyeDW8=,tag:K3KF4yVVxUgb5uTdCNkT3w==,type:str]
kind: ENC[AES256_GCM,data:N1fzrrCH,iv:lKEcZEkqXfi/9CAE6jJQCYRH4ju23sXvk+hf36Vp8rY=,tag:nejAhPoL6i60y8VEeTKWiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AUL2iYPHX/oYPH3k0QQVrko=,iv:aR0F53Kd0O4W1SBMDsPho0SC8jqlk1KqxoDmCU4pZhg=,tag:RjLh/xCwKiK3mP7BapcKkw==,type:str]
    namespace: ENC[AES256_GCM,data:R/H24hod4+q0XmkPRxyXTDs=,iv:WqdlXDQGjeVc/rIqZgvd4/8P7yQdVpJi2JpmUUDUpKM=,tag:ogZhiMqXwCdlTHAJauKd4A==,type:str]
type: ENC[AES256_GCM,data:g+H8X8SI,iv:vOwh/he0nJ6ZRaHCGIqdlUZFU+b9/zSM7HWtSO53nnQ=,tag:gVSTtpKCnFjx4abai2MX3A==,type:str]
stringData:
    token: ENC[AES256_GCM,data:HuwoEC491J8nj+FpprfbOkg/Ivksn+tBk5NTjb1GzAM7pdaeCrjy17ZOKQJCoLZ8rA4MyIBaft997WfY7cq2nL1IiQk2fSwsfKFxlq0JYODrDzpbZkIrOfBlfL/VAfLkFSedr7StqhWS2rwdrCa9ubrk8rQpnUNdULi9A9GV4ujAIkcROWbFdSVQptFyld4ajjIGS98QIXda/BHd5ftSEbIEnKkbDctNj5UO2+759vLTRXBCXKEh,iv:8j8/o4b037woexREGmMykNzKZrdQSpfzAHusZF6mJ/Y=,tag:8RVlZC8ix1rAt7DoJoaemA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSjJrbFRBWndQZksxbDNz
            NGZxNW14bjh0YmF6OTQ5cDd4eFBQNFVlOVUwCjhsNDNxaU1qdytwRGxIODA2N1VV
            RUFia0pkVU9xWVNLdzE0VEkwMWpVU2cKLS0tIHFvMlRWMHlsM2MzTmliWGR6YXY0
            NnNUYjN6bzVtYWFlVStCZUdURnNmeTgKIs804bF1FYkNx8t0ZiEy2amjawPs/SIW
            8HMZodLMNdRqB+acAt6M8/DwM5ZEdGYe/XUoqB8F2tmf5OKbrJv/NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6v260f4z6za7df8t5x726h0q3uhnr89fkm2rjk3n3tk9xgfgsrqqj5dff
    lastmodified: "2026-06-01T23:23:03Z"
    mac: ENC[AES256_GCM,data:FMskHelm8xnP/5I3KQDAc9ltwB0kxvIXsol571XcWhu+dZQjcnhjARMME2yQMgdYzItfQrCGiYEdpvIQNM7aGTmjrlrf5bcMbIvrsr40X9l1Lgupg+zUl8NxtUJVw4KNa87Y7jIlK8UR8jWp50sLYIwhv9lsYnr6uLA0v+WXOHU=,iv:2vrRND/NbUwFvR10h7iyX4f+cvMGycdpvmv5j7YzgsM=,tag:nmjQOelsiQETzEeFlTBT3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
