apiVersion: ENC[AES256_GCM,data:/CM=,iv:yZ5rMSaMTuGFx+xeAM8P5j7seBUcoWhNV/W+N5jHoxY=,tag:5fCg4u8xs0rAO/d7YO434A==,type:str]
kind: ENC[AES256_GCM,data:s6az/wj0,iv:LHaVlyBkUUfXTMI6gIeLCFRzU9oaxEr+1uPIuq6mQ44=,tag:e3iG3Ots0PsgI28+GaSfWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BrOLbMEUaCPQnbQWNw==,iv:YT7nXdXUpvPjz2MZdtO8aqmUJrKrONzEmTnf96gPvIM=,tag:VZb7qvrkjnZoRN17ZMhMFA==,type:str]
    namespace: ENC[AES256_GCM,data:4GgyfWpwsVaNIw==,iv:WI9xFXitYA4bDIMJ5HKui72fpZXjVV2Ra3CBilsZlRg=,tag:YpntYMn6zpyCXMkdbIs/iA==,type:str]
type: ENC[AES256_GCM,data:+Z7oPXAL,iv:KjbLCLVCy0Vsmd0AoizaTTopC4g2bpa3x8M/Xxt/ziA=,tag:+F4JxN8MV8K0CpmcU4V/AQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:iar/paw=,iv:V/X1Fk+XuHDHkk5MXri0VdhX2qx4QMfxsMuWEzm50ak=,tag:W7ZCnwJICTLYxyps0WbuQQ==,type:str]
    admin-password: ENC[AES256_GCM,data:wwuWN4ERuNyHrK8=,iv:ALFEoBrskH/tKVE7wXddB0ySmVISoCnCN1kZsuDy4Og=,tag:QvkmvWcBEYrZWqYXhoO/6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYXpIRUpuV0wxMEJkYjI2
            WUw0WFBtU09YTEVjNzdPZjdUbWRxN3kvWjNzCmNEc3c5S3lWWUFwMnZMdkhqU0RL
            bHUwTXlpR252bVQxMlo4V09QdUJ1RDQKLS0tIHpKTHdGc2x5ZG12eGhCcmZRanJY
            MklNSGNaS3BNQURUNlErUlpuRktBOVkK709CmtDffhuyRkje8okOM4BtS94y56nw
            +tT+N39WxcYmsAyc6Dkdq/i5ajYmdn00DTdKeF4eQhOgTQpR1Bc4qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6v260f4z6za7df8t5x726h0q3uhnr89fkm2rjk3n3tk9xgfgsrqqj5dff
    lastmodified: "2026-06-01T23:29:17Z"
    mac: ENC[AES256_GCM,data:RdYAirL8yYYUzZ60SBL17UIvQRmTZZpNTgA1+r81WnHrS3uvrdbGKvROLy07iCR6g5auyDQusudwOEXl9EGCeSaryKXa+8OcuUgTRHqFU6En0PNTWtFwdTYLRUzqOvZW8oDciRy9u1Dv3ybZJUDID8wN/StiuTIV/ri7G1tJZiA=,iv:UBit8lIX56IptFg2jNF7zsuM+ecQzPFRAtxafKdgRDk=,tag:t3DUpHPoLe1s4imDDIDUXw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
