apiVersion: ENC[AES256_GCM,data:mJQ=,iv:NtQthqeHbxJ3iD0w8PFt7oouk0nBZ6u+cfdZz16A5Ps=,tag:LCCuwLEw472OjIMZ1yc6Qw==,type:str]
kind: ENC[AES256_GCM,data:bB36kPnJ,iv:A77KMihxchyjszYY3I7yilGY7sUkA3BzX3eWRs982Cg=,tag:fhEma+1Lqr/CvXjXv2Q87w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FKssLniMFPcAxGFKZUJyr7qlHgwd,iv:AKYLpm9fH+05Phvho6Xiv04nm0BCk2Ml7mXDKskmnSc=,tag:odjFDEaeGvpAH6L4sZcXgg==,type:str]
    namespace: ENC[AES256_GCM,data:Pz/JRzmUqOhWYw8=,iv:gGzkMtRXJAw5lA5/PvUePT6qC973EXzon1QuEj06oZ8=,tag:IaenCyJqXUW7XRke6zrw+A==,type:str]
    labels:
        cnpg.io/reload: ENC[AES256_GCM,data:C5VD1w==,iv:wrtAQE+DSz6LaozKJI15acdW6/5TskjU1XxOAXF3wSw=,tag:MjK3fT+DUe3xKe+szLdLUQ==,type:str]
type: ENC[AES256_GCM,data:DEn/B9IC8l/ZNxR5LBfl7T6hbIkNmJA3,iv:RSXyZ7F0sOk6My52shiqXXYH56OC+7xx8YBNYWgr8BI=,tag:ehLXwq4iJWdX+Es55wfUNg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:t/voqE7IDoE=,iv:2YJLc42tzM3LTfAXIIyUZxnj2RWps8i7GyQqjB/XCi0=,tag:sLrU9s+iOig1hIINq0tQeA==,type:str]
    password: ENC[AES256_GCM,data:NXOUomITruiQpAJy5KKDpLT6PSuLN3lYF6swkN9+5Z3bhfJCR/sn9I8c7Co=,iv:Z3LvYujahQZUOppmlayt40yrAOC+g8xuMpoD/R04270=,tag:tpEL4l5Do7QTp/BDDuYkxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZE5qMnZWOGRENjArMDIw
            bGo1amZ1OTJxc04wbm5LRDRZSzFEUXpHSlFBCkp2YlUvT0w4SjdES25YbFczM0lG
            NEdiS1ZROUhHVXRmOTAvNzZFNEhudmcKLS0tIDdhVm11Mm9UUlBxNmowY2VyZDVS
            bndUeVczUGE0Q3ZKWlBHTHpLTmllc3MK21mtkAaamVTvptRZ//0F2eE8Cvinczku
            Os5CdNIF5pHppkXDiUSxMhXWLhi0fKbRoy6iFp1JKFyhpKffNLugMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6v260f4z6za7df8t5x726h0q3uhnr89fkm2rjk3n3tk9xgfgsrqqj5dff
    lastmodified: "2026-06-11T23:44:51Z"
    mac: ENC[AES256_GCM,data:K10NCL8rfhSEzAFUu+UUKp3luNmnARWX2mLXsr+zvJuBEykINBdH8xsPSqwPWQ1X+ykahQ9dyx6kyNUWVYzmpVLEKQwgSSCnrcnS/axtMfWl5kAVyIvZf112qSLbZnv9NcdtNihPbH7Dtdov/RLowP7V8voKDGxEqI7Ffst8Y4Q=,iv:Jukl0zUx39prFHsT4vPECy3h9qGlNChdVatno99UEXs=,tag:1YOaGv+0fJn74BW703Avaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
