apiVersion: ENC[AES256_GCM,data:5Lo=,iv:w5pQE98QoMA8rPWa1TlDrjEu6TKSpDwPFIOT6x1+gIc=,tag:VLR0J9Mvcz2pQx0YxItqgA==,type:str]
kind: ENC[AES256_GCM,data:KU45ZRGN,iv:PRYlDhFqWIHkIcstRTYuGAdnAVTWrUQIaS1Rt1VO9Bs=,tag:ZflBurWCofsmHzemNOT8+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UELuvXSCXrQSTVnpdV/y,iv:8PPhtb2WD9EhBgN3+ARRs/pPBHNXttsfXux98gvn9rA=,tag:dQMDAZt6dboBttw0pKcNyg==,type:str]
    namespace: ENC[AES256_GCM,data:bHHiAgyVwe16PGM=,iv:tbe7NHPFOwNF/hKSgS1lT37PIQ0CT/5HofIwcmpYOcw=,tag:4/r6NgEoqrrRIhW98O5iEA==,type:str]
type: ENC[AES256_GCM,data:IMHQ44RJrZfSqYiKi3/iBV/KuxayfprU,iv:72KUiAO99ray3cZzH35FqW4oqvmJhcTUfEuRwBHxNm8=,tag:vWzbqZgAVV+FosiL1vr7GQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:qJQ4,iv:tOwSZoI9HHLtq+I3b5vcxngl/XYAgdTYEoBKN7MgzM8=,tag:Tc9p8ik1Jcuco8Eww8Sh4g==,type:str]
    password: ENC[AES256_GCM,data:A0KKWSjS5EZ4DRRU50xtreROvpSURb0aRIX2FwUEJbwi9PJOFu2GqveSjYU=,iv:hud/1ubV3Soh4yCY4azSe03Z8Nft+QDYwOKtY+wcXKc=,tag:goQ95/5jOtUJoV43MPxCzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRmg4NUtTcnFTQ1NWSjE0
            TzNVWHB2bHNabzNCMFZhNXFpeVFweEtHTHpRCm1wS2F1YnZYQkpmVTl2OGFPY1Zn
            L2p2cWdGUkV3eTI1Rkp2T0dOaWEwWWsKLS0tIEg4b2VpSktPOWdWSXRBT0Z1c0pX
            SEN2OVI3bmNIeEFmWkpjQ1V2MUh2bGcKnzxaSnzYSbWW2yoIrWxAXXiP+fO7sbOK
            28KLQLFgMJnpV0kZuc4SK9u8wx1I/vT0K0KV24khrSWb/bWaegiFhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6v260f4z6za7df8t5x726h0q3uhnr89fkm2rjk3n3tk9xgfgsrqqj5dff
    lastmodified: "2026-06-10T09:00:40Z"
    mac: ENC[AES256_GCM,data:o/3vBB/MwtSxeG5mnuYpQzVM/l83UwSH8ATY2Mwt7H5oX53ql4MRoQzdYABWrv7Q/Gi4Q5A5Nn3Kukn0LpKRPyj/N+076hH4lxksCkIQB14I/Mp7j+8EkzYwItM5QyPRM7FH12D818X8PQjCFzB3eG7YOSzbI9kEAE6HfKd4jbU=,iv:QUsaqHDjhME4/UCzin8kgUi9RKjmp2T74j5uAkKMr8s=,tag:kkKBEwYQ7kWh38ThDFf5RA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:5Lo=,iv:w5pQE98QoMA8rPWa1TlDrjEu6TKSpDwPFIOT6x1+gIc=,tag:VLR0J9Mvcz2pQx0YxItqgA==,type:str]
kind: ENC[AES256_GCM,data:KU45ZRGN,iv:PRYlDhFqWIHkIcstRTYuGAdnAVTWrUQIaS1Rt1VO9Bs=,tag:ZflBurWCofsmHzemNOT8+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qNxAwjwUHWhF3bN3HXdggt/v2g==,iv:e6ENTXRHpLqS/2ndxSrPEGSXV5NwIeTamMoxGrk2CbQ=,tag:Jnh6XCfMAmFodnG2eUewug==,type:str]
    namespace: ENC[AES256_GCM,data:oJvBTyWrPosVeygTs2PE,iv:/ucsK2yryONXw8iB9d4NA9n+5C/i+fL4YaNS0aDCkhc=,tag:BAyzuTOKAzSbB2IHjuzkaQ==,type:str]
type: ENC[AES256_GCM,data:JdVGix1e,iv:9OslQHLsFh6VkZy9wVcsXrZ0WtOUVLCey3nuHhyLXA8=,tag:XRSn5oOMsJFnN+O2IYvlZw==,type:str]
stringData:
    database-name: ENC[AES256_GCM,data:2cXWWSh9vS474qwMIvE=,iv:kP3rhIKAo+kB3OvStTusBpPed1A9JCf8JYlg9xgUS9M=,tag:3N77cYDo2vGjFn+avS0nmQ==,type:str]
    database-user: ENC[AES256_GCM,data:we+KLu/mUQM=,iv:ruNLJlb7XskEZlKr32R57x7oUn72atjeO1/lvKvmpZE=,tag:KCZ7aL5cEvU7HH1IXiv4WA==,type:str]
    database-password: ENC[AES256_GCM,data:gg0+Sa04jOSWD1WYJe/QbsGOmr+0n2ibJMboMvf8+CZn69grC6TXsNjGOtA=,iv:WXLmblHa/PFaJlU0LnB+/KtyKgbHkjrpTWBoUK63rPs=,tag:M7cuUi3LmcwUPVbN6mdvZQ==,type:str]
    encryption-key: ENC[AES256_GCM,data:IkgjM8B+Hxh6zYK9rMrRhKIBY2bDxFlHsj6JAwymP5z1uG57MM7SgKx0VIw=,iv:ph71Aeratk4QPAkPeRZEmRo6fxNiTcjP+0740NxL0ac=,tag:dR/v/FhSvnRe6GiuSs5tig==,type:str]
    admin-password: ENC[AES256_GCM,data:RdpQDShxyY8C0S0ZZG2WocuFxjZ6ZzN7bnTftERgy1UbVV0g1XCdckVZaXI=,iv:qReKI0iS5dkB83t0gvZDgJ5ET7Z4PBb8rngpFO+9Udg=,tag:RqFienyW2a6GmnI2irLFJw==,type:str]
    session-token: ENC[AES256_GCM,data:CPP0Nrhype0gEuJNPQopChZDPnG14LqXo8AUOQyxdZY35F67vKe6Ypmyx5k=,iv:olFpQIC8l4wxAlkgmuM+60T30ULGh/KzYVNh7MoL2Mc=,tag:6VYbqEHFlZ16VHRA19ytOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRmg4NUtTcnFTQ1NWSjE0
            TzNVWHB2bHNabzNCMFZhNXFpeVFweEtHTHpRCm1wS2F1YnZYQkpmVTl2OGFPY1Zn
            L2p2cWdGUkV3eTI1Rkp2T0dOaWEwWWsKLS0tIEg4b2VpSktPOWdWSXRBT0Z1c0pX
            SEN2OVI3bmNIeEFmWkpjQ1V2MUh2bGcKnzxaSnzYSbWW2yoIrWxAXXiP+fO7sbOK
            28KLQLFgMJnpV0kZuc4SK9u8wx1I/vT0K0KV24khrSWb/bWaegiFhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6v260f4z6za7df8t5x726h0q3uhnr89fkm2rjk3n3tk9xgfgsrqqj5dff
    lastmodified: "2026-06-10T09:00:40Z"
    mac: ENC[AES256_GCM,data:o/3vBB/MwtSxeG5mnuYpQzVM/l83UwSH8ATY2Mwt7H5oX53ql4MRoQzdYABWrv7Q/Gi4Q5A5Nn3Kukn0LpKRPyj/N+076hH4lxksCkIQB14I/Mp7j+8EkzYwItM5QyPRM7FH12D818X8PQjCFzB3eG7YOSzbI9kEAE6HfKd4jbU=,iv:QUsaqHDjhME4/UCzin8kgUi9RKjmp2T74j5uAkKMr8s=,tag:kkKBEwYQ7kWh38ThDFf5RA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
