apiVersion: ENC[AES256_GCM,data:xqE=,iv:uB0WYfqrGeLojicaQqyAEi055oysK90QId3pDwfgz1s=,tag:8Cr2mndvIa2KJZrhDe9Tng==,type:str]
kind: ENC[AES256_GCM,data:mn//3Dnw,iv:sCQ6z+RH4fXDoza4ANKTymulhhE+JP71FiQ8Od6kkcY=,tag:I+TT5KFjhEJmvNcAmlhotg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:n3PBooP4cF57TtPqAgHs,iv:ZeU8AIQ4f302Ch4kP1j2ZcAYi4RTCM49fMN/PDZlGqE=,tag:O+8TGI8VPgFsKuYZK5j0Gw==,type:str]
    namespace: ENC[AES256_GCM,data:yoRLB8GZPNM4TIU=,iv:sqGy6dh4SsVb+DS/VPeWC2O6PC7EjX44lNpcW2Lq4Fw=,tag:6MMnVGmI7u3AxMs8Wli4sQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:87JCGmFJjH56jv0=,iv:HgadMhULJzS1wy/sy52qgn7TRhgxbiuZcvITYjWjrmA=,tag:8PNOBea2783LhEVk/lESPQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:M1jyz61ARMTGkE8Sl7GCPBZJTw==,iv:lLBR6QRGx1AJgzTcYrYiDFWo+aje2AAW4XOQEFUl5kk=,tag:bZbCzlz2+lnXygfskgt9jA==,type:str]
type: ENC[AES256_GCM,data:VL+qxKlUxCbgnFMAWmbr68V8k2S6r8sI,iv:4GqeCUYnbhdHcAumNYojqCMrcpQcoAa2/P7IMKkVpfo=,tag:bxZLtCO+xbT60t8hE9Em0A==,type:str]
stringData:
    username: ENC[AES256_GCM,data:ArPMj+9L6yY=,iv:hU80T0ZB7XtvHNx9vCleCKOGLBVJCFx2EToKJf74AHw=,tag:wKDTMmMbN1ge7sCZ76RXlw==,type:str]
    password: ENC[AES256_GCM,data:HY0z6jGQt85bhSVKNzgKHcafP9bLiDh/YBFRZsqtUSz7zN8t5PvjZtaqGhg=,iv:lBsJ39+ETj/WDpDf+MvGsUwypLenONH6DzlXW01yfE0=,tag:QXpVTze76uINwNus02enaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcDhYdFN6bUx0UEZTaWUw
            eCtYaGZiTzQxYWd3eGxuZkVjQTc1UWJWUFVjClBPTUMwODN3S2FSeXFMZ2tYcXpR
            RHJoN3ZJRUxhUWV4NVJuYThBb2ljYVkKLS0tIHlLMDBCYmdCOHVnVlFLSHlpL2hX
            d1BkUW01K0t1dTZHdTU5a0tUbnVJUEkK6vYB03dTQNV6bikWrBO2Rzr2SM42JvFm
            JSBbBdTatLeO7lgWfPu1hWYIBMGAFuteBch3eZtthFioTMh/bPn7JA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6v260f4z6za7df8t5x726h0q3uhnr89fkm2rjk3n3tk9xgfgsrqqj5dff
    lastmodified: "2026-06-11T21:07:27Z"
    mac: ENC[AES256_GCM,data:u4dq74oOYj7w0TP2WAkf8saJWZqD2m+KJ6X0Nm3pLSk7v1Og/+t2+s2ovrBsRoZ3slKSuDcnmk1zvuLRbI9hxPZ8uxSk33Gq5wzRmN/GEeCqbLBqQEH2/koa8S560k+NxZ7PxGr2OVhYUXwFvFocL6ed6se1dc+Czp2KWJalSUk=,iv:6S7iQvGa0HUcPvz0CWUIVziohkXurWoOlFV9F6QRFFI=,tag:vzo2nrXQBq8GioTdhBedYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
