apiVersion: ENC[AES256_GCM,data:0To=,iv:bWVtfCUXIFuqPBvIvz4yp1eyWXXqTuwGTcuWWQshtlw=,tag:r0xCCepojkCqi3hWWR2hkw==,type:str]
kind: ENC[AES256_GCM,data:0Syl5yvP,iv:oggOBF/sBhSvU4CCmD25PZ6khnuUvAGuH5zVsEYjVx4=,tag:AV1o30lbMOMYnrcNoWcn9w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hpqRGl+7JyQYsDpK7SeW,iv:Mx7ilBJDQLSufUos6SPQFnEY2wHBqnZKslvqXA3smio=,tag:FCiI+WLuvJfeTbiIIEEl8g==,type:str]
    namespace: ENC[AES256_GCM,data:lg8WG29VIyLqkMA=,iv:grQW76YkvTXuppdXH/tv/7SG/A72s3qJ6ZdxgbgkzFM=,tag:gN9TSZrq9L28PG8HeKcJXw==,type:str]
type: ENC[AES256_GCM,data:3QuZw2nP5smwTfrkHI/UyIGhmwTHrSRK,iv:52pxLwvqsYTGdC+3t4Z4A1JMIuyzFmkVG5vRqkLFNWQ=,tag:GVT9wHN/VDla7b9V76TFWw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:yXjb,iv:/LDNV6NtxlUMVpQJqCiVq6lFGIFQVycwuudHJ1TEuTU=,tag:mBpNGF6AGZJbHZl9ec6cEg==,type:str]
    password: ENC[AES256_GCM,data:YmH6PrpIA3KXLKxl+CBxbupaTTHPNQgShiOlTy5xtqSNcxo+xEdF3LwazcE=,iv:8CDyyUmsU7X+MN74fCT/17dSXPontiukC4M2sDtwDKo=,tag:ZKCdicyL84PtvAyZBbZAtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSkxpRmxUQzNYOHY3bVZu
            V2NydnUzYW9aVmRkd0NFcmdtT1BtTXpqZFFzCkRHTE5GeWZMY05jT1Z3VTR6NkZa
            UERjNVEvVEFLdElSRWpEMjN4RWtTZFkKLS0tIGJBeCtSVEhrakFZNkpQcHAyb1Q0
            MGQ1a01pUUZqNWdYbXhkUXRDTHduWjAK5hydbv5S0ZIheeoqP309tkN4u3SogHQI
            Tm4OAqVFto1olIoW4HKsg6lNuluqfmoM4Y3Bj5vMw+ioycoAjVI6kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6v260f4z6za7df8t5x726h0q3uhnr89fkm2rjk3n3tk9xgfgsrqqj5dff
    lastmodified: "2026-06-11T23:53:29Z"
    mac: ENC[AES256_GCM,data:/BwtOupChyp6HeLIuZPswcVLbIuDgmyWdqgC6XWjvylyJ2Qb8KXhs/bG+j2iuS/iEjanNO7UyMbK2jhIUhyoTcgN+EIQp4IvAf4nqEPP8Im7T431RROr8ekeKvhtgUrIMamWHBjv/ydFyQ1X9B3qrx+M8biXsnobacRNLewoDkU=,iv:vQb8Mxu1G/xCJOftnZa0oVTZHoz4knotzeVau+/mniE=,tag:ptZ6UfGUfYexX1BieItZYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:0To=,iv:bWVtfCUXIFuqPBvIvz4yp1eyWXXqTuwGTcuWWQshtlw=,tag:r0xCCepojkCqi3hWWR2hkw==,type:str]
kind: ENC[AES256_GCM,data:0Syl5yvP,iv:oggOBF/sBhSvU4CCmD25PZ6khnuUvAGuH5zVsEYjVx4=,tag:AV1o30lbMOMYnrcNoWcn9w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HHTfnonMK/cI0kUWhpqbsdUYRQ==,iv:tsQQXBk5nFrK5OjLefthZZwid3L7MZRz+GfH6a7xL3E=,tag:sHYzMcm3da4hE3ay4yU9vQ==,type:str]
    namespace: ENC[AES256_GCM,data:G0DJeUTDw0HSbR0cIll+,iv:HL4TTCHqhc6kYXPcZfvfzfObJ7X/+MK8RHBCs+gDn8c=,tag:VBwq4E25wO4qJkYmzemH6w==,type:str]
type: ENC[AES256_GCM,data:Oa0yjgVt,iv:Q2dstJL2zBov+exew7Ommn/6kQlZzheCRdtk28a20jA=,tag:jIP7q8fdBRDISliRu1Wp3A==,type:str]
stringData:
    database-name: ENC[AES256_GCM,data:2QiqvNU0PbqEFwh7PE8=,iv:onESNJT+je0zbtNvboVasPjdIpK3mlQ+w/UNL6d4Q7U=,tag:FtzyLtqYHEXR5bhz2fLv2Q==,type:str]
    database-user: ENC[AES256_GCM,data:ixYFB4a0ZxY=,iv:IaZSz8ZGnTlasGZddadsokBbgNDp+1Lts6xmuySmzNQ=,tag:rhYY7HcliNgxdga8G4VooQ==,type:str]
    database-password: ENC[AES256_GCM,data:Bzg8tso5b99du0r3o/BeSA4Gfn9ZjKborNSpKLjhc6gy7SyxixyvfH96yvM=,iv:G3wQc+irZZaL3v2sV+7OYZYEp9V/ms85i+d/IAwmpvw=,tag:DEOMnbjwyZdDiPuBqw27vw==,type:str]
    encryption-key: ENC[AES256_GCM,data:LndRu7xLSiBc9EG4jdFizosM9w7fhvRGk9T8RYE6FTvsYOJaE8M0ztlOA5Y=,iv:MtkrKLTC69px+B8Nd0ABTdCo8OXEkBFlguPYwE213CU=,tag:z0ueZFHwP+4H6Dzxi6n+tQ==,type:str]
    admin-password: ENC[AES256_GCM,data:VFgEarPvI1vRKhdzFcg+muK4ui0iKAxlMLhz7q1bezz+qPybCfPRT3PMQNo=,iv:7Bia8brqoa8B5Jcj0OhuzJhkwEM6elReq8QuSKEtGxg=,tag:Iv2LWrPJc520+0V1US6t7A==,type:str]
    auth-secret: ENC[AES256_GCM,data:SQriTe65vjW3BJgZXecEg9XxCXXDfRfhagdA6xjQkHyMe4+r9O5YfiFkd/k=,iv:230syNRvGWboZ4mIirSsTxSpn439uEtuXm2gAzeKw1c=,tag:h2HcparyM1E6xVRzIfAAhg==,type:str]
    auth-jwks-url: ENC[AES256_GCM,data:v4QptzEH7Mc6hsAQnLWws1BewMK3UnRKIQwt9hsMenaNx4LY81I=,iv:fTioDRBGgwY1kZdRhTAqzAXhcLFd2PIzTlG2dTeJg10=,tag:FDeWWFuHhI1mi6qUnEhUGA==,type:str]
    auth-issuer: ENC[AES256_GCM,data:1dTV7EnNaRYLnY1QJ+Pa6ASA+H3aCyDg,iv:m8StL8t+yKhSxRNpsk4ey0N4QXpEiQfuskuOWehxIQk=,tag:bG/t9J+4CW1sIRw5vJABmA==,type:str]
    auth-audience: ENC[AES256_GCM,data:POG/iz32fW14m0l5,iv:5JJn0GJpLqIIHFiFqzBA5t/GYxetbkUa44/D6k8UheU=,tag:6Hr5hRaZom0sD1oQ6OPw6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSkxpRmxUQzNYOHY3bVZu
            V2NydnUzYW9aVmRkd0NFcmdtT1BtTXpqZFFzCkRHTE5GeWZMY05jT1Z3VTR6NkZa
            UERjNVEvVEFLdElSRWpEMjN4RWtTZFkKLS0tIGJBeCtSVEhrakFZNkpQcHAyb1Q0
            MGQ1a01pUUZqNWdYbXhkUXRDTHduWjAK5hydbv5S0ZIheeoqP309tkN4u3SogHQI
            Tm4OAqVFto1olIoW4HKsg6lNuluqfmoM4Y3Bj5vMw+ioycoAjVI6kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6v260f4z6za7df8t5x726h0q3uhnr89fkm2rjk3n3tk9xgfgsrqqj5dff
    lastmodified: "2026-06-11T23:53:29Z"
    mac: ENC[AES256_GCM,data:/BwtOupChyp6HeLIuZPswcVLbIuDgmyWdqgC6XWjvylyJ2Qb8KXhs/bG+j2iuS/iEjanNO7UyMbK2jhIUhyoTcgN+EIQp4IvAf4nqEPP8Im7T431RROr8ekeKvhtgUrIMamWHBjv/ydFyQ1X9B3qrx+M8biXsnobacRNLewoDkU=,iv:vQb8Mxu1G/xCJOftnZa0oVTZHoz4knotzeVau+/mniE=,tag:ptZ6UfGUfYexX1BieItZYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
