apiVersion: ENC[AES256_GCM,data:M+s=,iv:Ow7Z2lDKxpvokUYGDKGsN0ehOCHULjIbuGWSSlCY9Ms=,tag:26iz0AWzEQdX1Pgc58yVZg==,type:str]
kind: ENC[AES256_GCM,data:DBV8TaEw,iv:Id3aJX3fhkEEE3h+LYwZC8Xakn2F+c/NNyVlSXamRU8=,tag:uHg8evKuRbbInxlxLUwRHA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oTXRERKnTdH5SVPzoQTW,iv:SIKUU7vA3pwYJUycPxU4jBtyS0j4XcMGSBXyKSk8xIc=,tag:M4T2JBYDbcmrdz/MpKPOkw==,type:str]
    namespace: ENC[AES256_GCM,data:mNwkG2gJtwwL868=,iv:uGnIj71Wh56CfqntrpxvhCNuAMSl6X3vtI9R54IQnt0=,tag:qbOLNwGptoMfNmPOD7wW0w==,type:str]
type: ENC[AES256_GCM,data:peqT348rR9U9xbv7lqVNp6uNs9TUDjza,iv:X1ahCDPivuimWMSF9gYZ6LAn7EP/vHg+gE77DeI73Cg=,tag:yl+HR6LDsigzhNYcYVlgAQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:0SOr,iv:vlEFN/mY32lrWp0phQCaEhDiwk+MYUGGQH5kpIKUUcU=,tag:+PnhKMkouWRXooPP6etVxQ==,type:str]
    password: ENC[AES256_GCM,data:wJW4FwOfJO7nk1Bx5jMCA3uWaayrH5feMBrpGkyKAgjDbZn4DWNeMmO6/+s=,iv:sVMz4Rhkp9JSGb5nbzt1kbB3tOPlC2gHcxreP5PDC+I=,tag:VyvV4p5unP+VrZhT/3PIyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvKzYybTVLa0FLbXgzdWpP
            Zk0vbEY5bVBuUnh1ekZ1OTM3SEF4Wlh1LzJFCmVuajgyU05QRytVNElscC84ejlv
            bmc1bTAxcDRoQTQ3dFVNRWdPYm5wdkUKLS0tIEN3dzN4UWkwT2MrQklYNkk4RHRF
            cG5HdHpmYzNEVkRIdmdBQi9nSE5DYkkKM3nhxf+t02gpMdYzuABvuVY4enYgmSCV
            sev6Z8dYtjhN9hNMn+CI6c0e8Y5pZTvK0G9dAB68HeAh4Qlu5Q4+mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6v260f4z6za7df8t5x726h0q3uhnr89fkm2rjk3n3tk9xgfgsrqqj5dff
    lastmodified: "2026-06-13T15:24:26Z"
    mac: ENC[AES256_GCM,data:uFJAM1xT3x/YLvHzNEm3JQIVs8qVK3/tuurRYixpgrmoovlikT82Q2YdxRlQVyq0hn+lN/VhgSU13I6/f1nDEFhjTgDB2UJ0vUgmQ4RQLNsjJapk3d+VvIYNEqpUl0ODfZB5EZLr6bVMoegLzoabJNepxWdtHsaseqRaE6vo3FE=,iv:IxuIgStkMKWGwd3Apo9opMNxdspa69y4B9XkLDNNlUE=,tag:LJzMbX3cV9JTb3twIX+NDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:ZGM=,iv:gdx6LowKFg1SoqBGXocPwJgk5nEMInVaWg8TsulW/WA=,tag:fHDPVtdRXyAzlogjv9oNFw==,type:str]
kind: ENC[AES256_GCM,data:Xh5iQE8M,iv:r36jnBu7B4b1aizrCdmZYDPhnyJge5QS20fo8abgbOs=,tag:/sUU0yQImH56NsemzttdUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QVF5EnuAOcTFI4DLKqItGnuVAg==,iv:bx2BJ6/4RtOR8xNTzOYIO71x33vgTENdLvgxL72/O/M=,tag:SoPwsefgnmw6MqbgYyaxeQ==,type:str]
    namespace: ENC[AES256_GCM,data:e+QivKkqiVw30mj9mTC2,iv:6ouVxiRF76N0FpFU/diC7BgeIQU3wSG6iMRipYSoObI=,tag:TApFN/czStCpaeoR9IBSlw==,type:str]
type: ENC[AES256_GCM,data:WY0Cv2TV,iv:ql7tY8LxcQmTXzibOJRvdKJCJPfKhsU8tdox6DPPHWk=,tag:SNzKGTmGkLckfMRJFgsaWw==,type:str]
stringData:
    database-name: ENC[AES256_GCM,data:v3bHoPSkRivXa/+xPA8=,iv:7Bw9zJ9VUdDq/F5zmy+cDg9u9K1V7barj5FTHXh43hk=,tag:juz4aVse8y17xi/uWmRG5w==,type:str]
    database-user: ENC[AES256_GCM,data:Vl79Zpe+SmQ=,iv:EnUdkUx+iQF8EqJOuajUCtRYtNkQ6hR4ZN8HSZ3H7JY=,tag:OAe0Dt6AgOUr5kAnmErxlw==,type:str]
    database-password: ENC[AES256_GCM,data:PfvuaiuEcNgeAGAZTLB6hmR242nyKEZFMC+itCVKXk8roHZRualDVT/nMoo=,iv:9/uDjAEccxPiRUEUTEQtWZ2uQUDuJrWtzlcl7HXq15g=,tag:StuI6PaVRkKQMh8DSTCehQ==,type:str]
    encryption-key: ENC[AES256_GCM,data:yYsIbk44wcLn7l7NgEVzjRzw1RoqWSQK1XcNSnCVRcwkaF5YB9MHoxDmibE=,iv:leaVboGxjzOh1XiBeFCZjylbFTSI74EY3yPTd45Oaoc=,tag:2Tb2gxM3g86GADzJDZctsw==,type:str]
    admin-password: ENC[AES256_GCM,data:pailhReAs1i/vq5PI8Y=,iv:+A9TgyoQtPLGg+fWeuC96zf46xirL0FyczuWJGdw0Jg=,tag:RQLp0h0ZOBAEyqf3Rwv83Q==,type:str]
    auth-secret: ENC[AES256_GCM,data:iNxpbx4t9wtzG5c6LlY9K7hE3Nutpw8OmqolYEjA1x9JEEFTTC26Dxam+Ls=,iv:TaGtmsf2ijCcIzWs4gg2zpu/iurzThM4xhwGrYScIQQ=,tag:gKt1hTzw5acKKsVgeoIxTA==,type:str]
    auth-jwks-url: ENC[AES256_GCM,data:EicOiby1uxPbUBrLfip+QaFPryK5fL/Kh3qCVGs+o+tdBDV9mdI=,iv:Pip8B+8upu9ZJfrVlFg+Lnx3lF8Wr8AuJTTQqkl5Smo=,tag:4VIEiVm7IzFK1fO8FuCyvQ==,type:str]
    auth-issuer: ENC[AES256_GCM,data:JQmOnTw1oggDDeAffC+Mt1XhMbQvtfeQ,iv:33iPfeeTGTLnw8wUJQfRQwDRb9J4Xn93Fj2//tmIlXM=,tag:TOxHaufocDCzLppUwVI7WQ==,type:str]
    auth-audience: ENC[AES256_GCM,data:rg57wg9mkbOqT/J2,iv:CV9tOKJZ5w71BkWFIGJakycDOPGg1X7zuYF3bg/8HuE=,tag:5/P0542rc5U4ntFWF+ZLlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvKzYybTVLa0FLbXgzdWpP
            Zk0vbEY5bVBuUnh1ekZ1OTM3SEF4Wlh1LzJFCmVuajgyU05QRytVNElscC84ejlv
            bmc1bTAxcDRoQTQ3dFVNRWdPYm5wdkUKLS0tIEN3dzN4UWkwT2MrQklYNkk4RHRF
            cG5HdHpmYzNEVkRIdmdBQi9nSE5DYkkKM3nhxf+t02gpMdYzuABvuVY4enYgmSCV
            sev6Z8dYtjhN9hNMn+CI6c0e8Y5pZTvK0G9dAB68HeAh4Qlu5Q4+mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6v260f4z6za7df8t5x726h0q3uhnr89fkm2rjk3n3tk9xgfgsrqqj5dff
    lastmodified: "2026-06-13T15:24:26Z"
    mac: ENC[AES256_GCM,data:uFJAM1xT3x/YLvHzNEm3JQIVs8qVK3/tuurRYixpgrmoovlikT82Q2YdxRlQVyq0hn+lN/VhgSU13I6/f1nDEFhjTgDB2UJ0vUgmQ4RQLNsjJapk3d+VvIYNEqpUl0ODfZB5EZLr6bVMoegLzoabJNepxWdtHsaseqRaE6vo3FE=,iv:IxuIgStkMKWGwd3Apo9opMNxdspa69y4B9XkLDNNlUE=,tag:LJzMbX3cV9JTb3twIX+NDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
