apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yml
  - certificates.yml
  - addons.yml
  - platform.yml
  - platform-database.yml
  - platform-api.yml
  - platform-frontend.yml
  - apps.yml
