apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-frontend
  namespace: flux-system
spec:
  dependsOn:
    - name: platform-api
  interval: 10m
  path: ./kubernetes/platform/frontend
  prune: true
  sourceRef:
    kind: GitRepository
    name: edinstance-lab
  timeout: 5m
  wait: true
