apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: edinstance-lab
  timeout: 2m
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
