apiVersion: v1
kind: Secret
metadata:
  name: platform-db-app
  namespace: platform-db
  labels:
    app.kubernetes.io/name: platform-db
    app.kubernetes.io/part-of: edinstance-platform
type: kubernetes.io/basic-auth
stringData:
  username: app
  password: change-me-before-apply
