[k8s_control_plane]
k8s-1 ansible_host=192.168.2.10
k8s-2 ansible_host=192.168.2.11
k8s-3 ansible_host=192.168.2.12

[k8s_workers]
k8s-1
k8s-2
k8s-3

[k8s_nodes:children]
k8s_control_plane
k8s_workers

[k8s_nodes:vars]
ansible_user=edward
ansible_become=true
ansible_python_interpreter=/usr/bin/python3
