apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  loki.yml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://monitoring-loki-gateway.monitoring.svc.cluster.local
        jsonData:
          timeout: 60
          maxLines: 5000
          derivedFields:
            - name: TraceID
              matcherRegex: '"trace_id"\s*:\s*"([a-f0-9]{32})"'
              datasourceUid: tempo
              url: '$${__value.raw}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-tempo
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  tempo.yml: |-
    apiVersion: 1
    datasources:
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3200
        jsonData:
          nodeGraph:
            enabled: true
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: '-1m'
            spanEndTimeShift: '1m'
            tags:
              - key: k8s.namespace.name
                value: namespace
              - key: k8s.pod.name
                value: pod
              - key: k8s.container.name
                value: container
            filterByTraceID: true
            filterBySpanID: false
          tracesToMetrics:
            datasourceUid: prometheus
            spanStartTimeShift: '-1m'
            spanEndTimeShift: '1m'
            tags:
              - key: service.name
                value: service_name
            queries:
              - name: Request rate
                query: 'sum(rate(http_server_request_duration_seconds_count{$$__tags}[5m]))'
              - name: Error rate
                query: 'sum(rate(http_server_request_duration_seconds_count{$$__tags,http_response_status_code=~"5.."}[5m]))'
