apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - helmrepository.yml
  - values-configmap.yml
  - kube-prometheus-stack.yml
  - dashboards.yml
  - grafana-route.yml
  - networkpolicy.yml
