apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-values
  namespace: flux-system
data:
  values.yml: |
    fullnameOverride: kube-prometheus-stack

    prometheusOperator:
      tls:
        enabled: false
      admissionWebhooks:
        enabled: false
        patch:
          enabled: false
        deployment:
          tls:
            enabled: false

    alertmanager:
      enabled: false
      alertmanagerSpec:
        replicas: 1
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

    grafana:
      replicas: 1
      defaultDashboardsTimezone: browser
      admin:
        existingSecret: grafana-admin
        userKey: admin-user
        passwordKey: admin-password
      persistence:
        enabled: true
        size: 10Gi
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      sidecar:
        dashboards:
          enabled: true
        datasources:
          enabled: true

    prometheus:
      prometheusSpec:
        replicas: 1
        retention: 15d
        scrapeInterval: 30s
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 3Gi

    nodeExporter:
      enabled: false

    prometheus-node-exporter:
      enabled: false

    kube-state-metrics:
      livenessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 5
        periodSeconds: 10
        failureThreshold: 6
      readinessProbe:
        initialDelaySeconds: 30
        timeoutSeconds: 5
        periodSeconds: 10
        failureThreshold: 6
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 256Mi
