apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-values
  namespace: flux-system
data:
  values.yml: |
    replicas: 1
    tempo:
      retention: 168h
      reportingEnabled: false
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: "1"
          memory: 1Gi
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
          wal:
            path: /var/tempo/wal
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 10Gi
    service:
      type: ClusterIP
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
